# Created by: haimkastner
# Created at: 2025-02-06 21:23:13 UTC

name: CI

on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: |
          go mod download

      - name: Run tests
        run: go test ./...
